### ISSUE TITLE
Infrastructure clean up

### ISSUE THREAD

**Issue by DFriend01** [DFriend01/os161_devcontainer#10]
## Todo List

- [x] Start using GitHub releases. ~Add assets to release to avoid pulling from mirror sites everytime the docker images build~
- [x] Remove `update-bashrc.sh` script
- [x] Replace `.vscode` directory with code-workspace file
- [x] Include tutorial (in markdown format) in repo documentation
- [x] Look into getting the C/C++ extension to support better navigation of OS161 source (click function to go the definition, hover for function signature, etc.)
  - Use clangd extension + bear to create database and enable better Intellisense. Need to disable Intellisense engine for C/C++ extension, also need to specify compile commands directory in clangd arguments for clangd to find it
  - Ubuntu 18.04 is too old to get this working well, so the base image may need to be upgraded to a newer version of Ubuntu
- [x] Remove unnecessary dependencies and vscode extensions
- [x] Fix VS Code debugger to step between MIPS assembly and C code (see `launch.json`/code-workspace file)
